from ModelosRepresentacao.modelosEstatisticos import ModelosEstatisticos
from ModelosRepresentacao.sentenceEmbeddings import SentenceEmbeddings
from ModelosRepresentacao.wordEmbeddings import WordEmbeddings

