from ExtracaoConhecimento.agrupamento import Agrupamento 
from ExtracaoConhecimento.compreensaoSemantica import CompreensaoSemantica 
from ExtracaoConhecimento.compreensaoEmocional import CompreensaoEmocional 
